(()=>{const dec=p=>{const r=atob(p.join("")),b=new Uint8Array(r.length);for(let i=0;i<r.length;i++)b[i]=r.charCodeAt(i);return URL.createObjectURL(new Blob([b],{type:"font/woff2"}))};const load=async(n,p)=>{const u=dec(p),f=new FontFace(n,`url(${u}) format("woff2")`);await f.load();document.fonts.add(f)};Promise.all([load("TX02",window.__FONT_TX||[]),load("HYHuaGuan",window.__FONT_HY||[])]).catch(()=>{});})();
(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const masterInput=$('#file'),drop=$('#drop'),reset=$('#reset'),frames=$$('.preview'),zoom=$('#zoom'),x=$('#x'),y=$('#y'),center=$('#center'),safe=$('#safe'),thirds=$('#thirds');
const slots={
 square:{input:$('#squareFile'),frame:$('#squareFrame'),thumb:$('#thumbSquare'),info:$('#squareInfo'),img:$('#squareFrame img'),thumbImg:$('#thumbSquare img'),file:null,url:null,w:0,h:0,independent:false},
 portrait:{input:$('#portraitFile'),frame:$('#portraitFrame'),thumb:$('#thumbPortrait'),info:$('#portraitInfo'),img:$('#portraitFrame img'),thumbImg:$('#thumbPortrait img'),file:null,url:null,w:0,h:0,independent:false}
};
let master=null;
const bytes=n=>{if(!Number.isFinite(n))return'—';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i?1:0)} ${u[i]}`};
const near=(w,h)=>{const r=w/h,p=[['1:1',1],['3:4',.75],['4:5',.8],['2:3',2/3],['16:9',16/9],['9:16',9/16]],n=p.reduce((a,b)=>Math.abs(b[1]-r)<Math.abs(a[1]-r)?b:a);return Math.abs(n[1]-r)<.025?n[0]:r.toFixed(3)};
function controls(){document.documentElement.style.setProperty('--zoom',+zoom.value/100);document.documentElement.style.setProperty('--px',x.value+'%');document.documentElement.style.setProperty('--py',y.value+'%');$('#zoomOut').textContent=zoom.value+'%';$('#xOut').textContent=x.value+'%';$('#yOut').textContent=y.value+'%'}
function guides(){frames.forEach(f=>{f.classList.toggle('guide-center',center.checked);f.classList.toggle('guide-safe',safe.checked);f.classList.toggle('guide-thirds',thirds.checked)})}
function quality(){const rd=$('#resDot'),rt=$('#resText'),pd=$('#ratioDot'),pt=$('#ratioText');if(!master){rd.className=pd.className='dot';rt.textContent='载入图片后检查像素。';pt.textContent='载入图片后检查原始比例。';return}const m=Math.min(master.w,master.h);if(m>=1600){rd.className='dot ok';rt.textContent=`默认图片像素充足：短边 ${m}px。`}else{rd.className='dot warn';rt.textContent=`默认图片短边 ${m}px；建议最终主图尽量 ≥1600px。`}const r=master.w/master.h;if(Math.abs(r-1)<.01||Math.abs(r-.75)<.01){pd.className='dot ok';pt.textContent=`默认图片原始比例接近 ${Math.abs(r-1)<.01?'1:1':'3:4'}。`}else{pd.className='dot warn';pt.textContent='默认图片不是 1:1 / 3:4，重点检查裁切后主体是否完整。'}}
function release(slot){if(slot.url)URL.revokeObjectURL(slot.url);slot.url=null}
function applySlot(slot,f,independent){if(!f||!f.type.startsWith('image/'))return;release(slot);const u=URL.createObjectURL(f),probe=new Image;probe.onload=()=>{slot.file=f;slot.url=u;slot.w=probe.naturalWidth;slot.h=probe.naturalHeight;slot.independent=independent;slot.img.src=u;slot.thumbImg.src=u;slot.frame.classList.add('has-image');slot.thumb.classList.add('has-image');slot.info.textContent=independent?`${f.name} · 独立素材`:'使用默认图片';slot.frame.querySelector('.source-badge').style.display=independent?'inline-block':'none';reset.disabled=false};probe.src=u}
function setMaster(f){if(!f||!f.type.startsWith('image/'))return;const probe=new Image,u=URL.createObjectURL(f);probe.onload=()=>{if(master?.url)URL.revokeObjectURL(master.url);master={file:f,url:u,w:probe.naturalWidth,h:probe.naturalHeight};$('#name').textContent=f.name||'粘贴图片';$('#dims').textContent=`${master.w} × ${master.h}px`;$('#ratio').textContent=near(master.w,master.h);$('#size').textContent=bytes(f.size);applySlot(slots.square,f,false);applySlot(slots.portrait,f,false);zoom.value=100;x.value=50;y.value=50;controls();quality()};probe.src=u}
function setIndependent(key,f){applySlot(slots[key],f,true)}
function clear(){if(master?.url)URL.revokeObjectURL(master.url);master=null;Object.values(slots).forEach(slot=>{release(slot);slot.file=null;slot.w=slot.h=0;slot.independent=false;slot.img.removeAttribute('src');slot.thumbImg.removeAttribute('src');slot.frame.classList.remove('has-image');slot.thumb.classList.remove('has-image');slot.info.textContent='使用默认图片';slot.frame.querySelector('.source-badge').style.display='none';slot.input.value=''});reset.disabled=true;masterInput.value='';$('#name').textContent=$('#dims').textContent=$('#ratio').textContent=$('#size').textContent='—';zoom.value=100;x.value=50;y.value=50;controls();quality()}
function exportCrop(frame){const slot=slots[frame.dataset.slot];if(!slot?.file||!slot.w||!slot.h)return;const ow=+frame.dataset.w,oh=+frame.dataset.h,c=document.createElement('canvas');c.width=ow;c.height=oh;const ctx=c.getContext('2d'),im=new Image;im.onload=()=>{const tr=ow/oh,sr=slot.w/slot.h,z=+zoom.value/100;let cw,ch;if(sr>tr){ch=slot.h/z;cw=ch*tr}else{cw=slot.w/z;ch=cw/tr}cw=Math.min(cw,slot.w);ch=Math.min(ch,slot.h);const sx=(slot.w-cw)*(+x.value/100),sy=(slot.h-ch)*(+y.value/100);ctx.drawImage(im,sx,sy,cw,ch,0,0,ow,oh);c.toBlob(b=>{if(!b)return;const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`main-image-${frame.dataset.ratio.replace(':','x')}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/jpeg',.94)};im.src=slot.url}
drop.onclick=()=>masterInput.click();drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();masterInput.click()}};masterInput.onchange=()=>setMaster(masterInput.files?.[0]);
['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>setMaster(e.dataTransfer?.files?.[0]));window.addEventListener('paste',e=>{const i=[...(e.clipboardData?.items||[])].find(i=>i.type.startsWith('image/'));if(i)setMaster(i.getAsFile())});
$$('.replace').forEach(b=>b.onclick=()=>slots[b.dataset.pick].input.click());slots.square.input.onchange=()=>setIndependent('square',slots.square.input.files?.[0]);slots.portrait.input.onchange=()=>setIndependent('portrait',slots.portrait.input.files?.[0]);
[zoom,x,y].forEach(v=>v.oninput=controls);[center,safe,thirds].forEach(v=>v.onchange=guides);reset.onclick=clear;frames.forEach(f=>f.querySelector('.export').onclick=()=>exportCrop(f));controls();guides();quality();
})();